FROM php:8.4-cli

# Update container and install redis extension
RUN apt-get update && apt-get upgrade -y \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/* /tmp/pear

# Set working directory
WORKDIR /var/www/html

# Default command
CMD ["php", "worker.php"]