name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Debug repo structure
      #   run: |
      #     pwd
      #     ls -la
      #     find . -maxdepth 2 -type d | sort

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, redis
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      # - name: Ensure remote folder exists
      #   run: |
      #     ssh "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" \
      #       "ls -la ~/Docker/backend/html"

      - name: Deploy API with rsync
        run: |
          rsync -azv --delete \
            --exclude='.env' \
            --exclude='tests' \
            --exclude='.git' \
            --exclude='.github' \
            --rsync-path="sudo rsync" \
            ./ \
            "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/Docker/backend/html"



      - name: Fix ownership after sudo rsync
        run: |
          ssh "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" "sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} ~/Docker/backend/html"

      - name: Create .env on server
        run: |
          ssh "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" << 'EOF'
          cat > ~/Docker/backend/html/.env << 'ENVFILE'
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          DB_NAME=${{ secrets.DB_NAME }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          ENVFILE
          EOF

      - name: Restart backend container
        run: |
          ssh "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" "docker compose restart backend"

          
      # - name: Fix permissions and warmup
      #   run: |
      #     ssh -p "${{ secrets.DEPLOY_PORT }}" "${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" << 'EOF'
      #       cd "${{ secrets.API_DEPLOY_PATH }}"
      #       mkdir -p storage/logs
      #       find storage -type d -exec chmod 775 {} \;
      #       find storage -type f -exec chmod 664 {} \;
      #     EOF


